/**
 * N8G Drive Sync — Audio Processor
 *
 * Reads audio file metadata and generates markdown + JSON.
 * Falls back to filename-based metadata when ffprobe isn't available.
 */

import * as fs from "fs";
import * as path from "path";
import { execSync } from "child_process";

function log(message: string) {
  const ts = new Date().toISOString();
  process.stdout.write(`[${ts}] [processor:audio] ${message}\n`);
}

export interface TrackMetadata {
  filename: string;
  title: string;
  artist: string;
  album: string;
  duration: string;
  format: string;
  sampleRate?: string;
  bitrate?: string;
  dateAdded: string;
  sizeBytes: number;
}

/**
 * Try to extract metadata using ffprobe.
 * Falls back gracefully if ffprobe isn't installed.
 */
function tryFfprobe(filePath: string): Partial<TrackMetadata> | null {
  try {
    const raw = execSync(
      `ffprobe -v quiet -print_format json -show_format -show_streams "${filePath}"`,
      { encoding: "utf-8", timeout: 5000 }
    );
    const data = JSON.parse(raw);

    const format = data.format || {};
    const stream = data.streams?.[0] || {};

    return {
      title: format.tags?.title || path.basename(filePath, path.extname(filePath)),
      artist: format.tags?.artist || "N8G",
      album: format.tags?.album || "",
      duration: format.duration
        ? formatDuration(parseFloat(format.duration))
        : "unknown",
      format: format.format_name || path.extname(filePath),
      sampleRate: stream.sample_rate ? `${stream.sample_rate} Hz` : undefined,
      bitrate: format.bit_rate
        ? `${(parseInt(format.bit_rate) / 1000).toFixed(0)} kbps`
        : undefined,
    };
  } catch {
    // ffprobe not available or failed — use fallback
    return null;
  }
}

function formatDuration(seconds: number): string {
  const m = Math.floor(seconds / 60);
  const s = Math.floor(seconds % 60);
  return `${m}:${s.toString().padStart(2, "0")}`;
}

/**
 * Read audio metadata. Uses ffprobe if available, otherwise filename-based.
 */
export function readAudioMetadata(filePath: string): TrackMetadata {
  const filename = path.basename(filePath);
  const ext = path.extname(filename).toLowerCase();
  const stats = fs.statSync(filePath);

  const ffprobe = tryFfprobe(filePath);

  return {
    filename,
    title: ffprobe?.title || path.basename(filename, ext).replace(/[-_]/g, " "),
    artist: ffprobe?.artist || "N8G",
    album: ffprobe?.album || "",
    duration: ffprobe?.duration || "unknown",
    format: ffprobe?.format || ext.slice(1).toUpperCase(),
    sampleRate: ffprobe?.sampleRate,
    bitrate: ffprobe?.bitrate,
    dateAdded: stats.birthtime.toISOString().split("T")[0],
    sizeBytes: stats.size,
  };
}

/**
 * Generate a markdown file for a single track.
 */
export function generateTrackMarkdown(
  track: TrackMetadata,
  outputDir: string,
  dryRun: boolean = false
): string {
  const slug = track.title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
  const mdPath = path.join(outputDir, `${slug}.md`);

  const content = `---
title: "${track.title}"
artist: "${track.artist}"
album: "${track.album}"
duration: "${track.duration}"
format: "${track.format}"
dateAdded: "${track.dateAdded}"
file: "${track.filename}"
size: "${(track.sizeBytes / (1024 * 1024)).toFixed(1)} MB"
${track.sampleRate ? `sampleRate: "${track.sampleRate}"` : ""}
${track.bitrate ? `bitrate: "${track.bitrate}"` : ""}
---

# ${track.title}

**Artist:** ${track.artist}
**Duration:** ${track.duration}
**Format:** ${track.format}
**Added:** ${track.dateAdded}

---

*Track metadata auto-generated by N8G Drive Sync.*
`;

  if (dryRun) {
    log(`[DRY RUN] Would write: ${mdPath}`);
    return mdPath;
  }

  fs.mkdirSync(outputDir, { recursive: true });
  fs.writeFileSync(mdPath, content, "utf-8");
  log(`Generated markdown: ${mdPath}`);
  return mdPath;
}

/**
 * Generate or update releases.json for an album folder.
 */
export function updateReleasesJson(
  tracks: TrackMetadata[],
  albumName: string,
  outputDir: string,
  dryRun: boolean = false
): string {
  const jsonPath = path.join(outputDir, "releases.json");

  interface ReleaseEntry {
    title: string;
    artist: string;
    duration: string;
    format: string;
    dateAdded: string;
    filename: string;
    sizeMb: string;
  }

  const entries: ReleaseEntry[] = tracks.map((t) => ({
    title: t.title,
    artist: t.artist,
    duration: t.duration,
    format: t.format,
    dateAdded: t.dateAdded,
    filename: t.filename,
    sizeMb: (t.sizeBytes / (1024 * 1024)).toFixed(1),
  }));

  const existingEntries: ReleaseEntry[] = [];
  if (fs.existsSync(jsonPath)) {
    try {
      const existing = JSON.parse(fs.readFileSync(jsonPath, "utf-8"));
      if (Array.isArray(existing)) {
        existingEntries.push(...existing);
      }
    } catch {
      // Corrupt file — start fresh
    }
  }

  // Merge: update existing, add new
  const merged = new Map<string, ReleaseEntry>();
  for (const e of existingEntries) merged.set(e.filename, e);
  for (const e of entries) merged.set(e.filename, e);

  const output = {
    album: albumName,
    updatedAt: new Date().toISOString(),
    tracks: [...merged.values()],
  };

  if (dryRun) {
    log(`[DRY RUN] Would write releases.json with ${merged.size} tracks`);
    return jsonPath;
  }

  fs.mkdirSync(outputDir, { recursive: true });
  fs.writeFileSync(jsonPath, JSON.stringify(output, null, 2), "utf-8");
  log(`Updated releases.json: ${merged.size} tracks`);
  return jsonPath;
}

/**
 * Process a single audio file: read metadata, generate markdown.
 */
export function processAudioFile(
  inputPath: string,
  outputDir: string,
  albumName: string = "",
  dryRun: boolean = false
): TrackMetadata {
  const track = readAudioMetadata(inputPath);
  track.album = albumName || track.album;
  generateTrackMarkdown(track, outputDir, dryRun);
  return track;
}

/**
 * Process all audio files in a directory (an album folder).
 */
export function processAlbumDirectory(
  dirPath: string,
  outputDir: string,
  albumName?: string,
  dryRun: boolean = false
): TrackMetadata[] {
  const name = albumName || path.basename(dirPath);
  const tracks: TrackMetadata[] = [];

  if (!fs.existsSync(dirPath)) {
    log(`Directory not found: ${dirPath}`);
    return tracks;
  }

  const audioExts = [".mp3", ".wav", ".flac", ".aac", ".ogg", ".m4a", ".aiff"];
  const entries = fs.readdirSync(dirPath);

  for (const entry of entries) {
    const ext = path.extname(entry).toLowerCase();
    if (!audioExts.includes(ext)) continue;

    const inputPath = path.join(dirPath, entry);
    if (!fs.statSync(inputPath).isFile()) continue;

    try {
      const track = processAudioFile(inputPath, outputDir, name, dryRun);
      tracks.push(track);
    } catch (err: any) {
      log(`ERROR processing ${entry}: ${err.message}`);
    }
  }

  // Generate releases.json if we found tracks
  if (tracks.length > 0) {
    updateReleasesJson(tracks, name, outputDir, dryRun);
  }

  return tracks;
}
